name: Docker Image CI
description: 'Runs kyverno cli'
branding:
  icon: 'command'
  color: 'red'
inputs:
  command:
    description: 'kyverno command to run'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.command }}
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    #  run: docker build -t asciitext-docker . local < Dockerfile
      run: docker build -t DOCKER_HUB_USER/kyverno-action:v1.0.0 .
    - name: Run the Docker image
      run: docker run DOCKER_HUB_USER/kyverno-action:v1.0.0 "kyverno version"
