name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    #  run: docker build -t asciitext-docker . local < Dockerfile
      run: |
        docker build -t asciitext-docker . local < Dockerfile
    #- name: Run the Docker image
    #  run: docker run DOCKER_HUB_USER/kyverno-action:v1.0.0 "kyverno version"
